### PR TITLE
Expose DataStreamReader.Schema() that takes in StructType

### PR DESCRIPTION
**Pull request by elvaliuliuliu**
This pr is the StructType Schema support for DataStreamReader.

It specifies the input schema that takes in StructType. By specifying the schema here, the underlying data source can skip the schema inference step, and thus speed up data loading.

### CODE REVIEW

**Comment by imback82** [comment]
why is this a follow up when the changes are the same?

**Comment by elvaliuliuliu** [comment]
@imback82 Sorry for the confusion. I have changed the description. This pr is the StructType Schema support for DataStreamReader. The other is for DataFrameReader. Thanks.

**Comment by imback82** [comment]
Can we do these in one PR please?

**Comment by elvaliuliuliu** [comment]
Sure, will close this and add them in one PR. Thanks.

**Pull request closed without merging**
