### PR TITLE
Move Microsoft.Spark.Experimental to Microsoft.Spark

### LINKED ISSUE #639: [Feature Request]: Move extensions in Microsoft.Spark.Experimental to Microsoft.Spark in 1.0
There are few extensions defined in `Microsoft.Spark.Experimental` for registering Vector UDFs and group UDFs (with both Arrow and .NET DataFrame support). I think this can live inside Microsoft.Spark when we move to 1.0.

Any thoughts?

### PR DESCRIPTION
**Pull request by suhsteve**
Moving experimental `Microsoft.Data.Analysis.DataFrame` support into `Microsoft.Spark`

Fixes #639.

### CODE REVIEW

**Comment by suhsteve** [comment]
Should we move the `VectorUdf` methods out of `Functions` and into it's own static class `ArrowFunctions` ?

**Comment by suhsteve** [comment]
> Should we move the `VectorUdf` methods out of `Functions` and into it's own static class `ArrowFunctions` ?

moved `VectorUdf` from `Functions` to `ArrowFunctions`

**Comment by imback82** [comment]
@Niharikadutta Can you capture this change in the migration guide?

**Review by imback82 — DISMISSED** [review]
LGTM, thanks @suhsteve!

**Comment by Niharikadutta** [comment]
> @Niharikadutta Can you capture this change in the migration guide?

Sorry, which migration guide?

**Comment by imback82** [comment]
1.0 doc? I thought we were planning to have a migration section?

**Comment by Niharikadutta** [comment]
> 1.0 doc? I thought we were planning to have a migration section?

We haven't chalked out a specific `1.0 doc` in #671 but we can discuss and talk about it to see what information it needs to contain.

**Comment by imback82** [comment]
@suhsteve Can you check the following failure? Is this also random?
```
Microsoft.Spark.UnitTest.CallbackTests.TestCallbackServer
Assert.Equal() Failure
Expected: 10
Actual:   8
```

**Comment by suhsteve** [comment]
> @suhsteve Can you check the following failure? Is this also random?
> 
> ```
> Microsoft.Spark.UnitTest.CallbackTests.TestCallbackServer
> Assert.Equal() Failure
> Expected: 10
> Actual:   8
> ```

This is related to our usage of threads.  There's an issue tracking this.  https://github.com/dotnet/spark/issues/685

**Comment by imback82** [comment]
@Niharikadutta Can you add a migration guide section to https://github.com/dotnet/spark/issues/671, and have a bullet that links to this PR?

**Review by Niharikadutta — COMMENTED** [review]
LGTM. Thanks @suhsteve !

**Pull request merged**
