### PR TITLE
Prep 0.9.0 release

### PR DESCRIPTION
**Pull request by elvaliuliuliu**
This PR prepares the v0.9.0 release.

### CODE REVIEW

**Comment by imback82** [comment]
Can you resolve the conflicts?

**Comment by elvaliuliuliu** [comment]
> Can you resolve the conflicts?

Updated it. Thanks.

**Comment by imback82** [comment]
Can you update this with #420?

**Comment by elvaliuliuliu** [comment]
> Can you update this with #420?

Added `DateType` support.

**Pull request merged**
