### PR TITLE
Fix issue where install-worker.sh was never called

### PR DESCRIPTION
**Pull request by gbrueckl**
install-worker.sh was never called and also the second parameter should be the URL only if the first parameter is "github"

We are excited to review your PR.

So we can do the best job, please check:

- [x] There's a descriptive title that will make sense to other developers some time from now. 
- [ ] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [x] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [ ] You have included any necessary tests in the same PR.

### CODE REVIEW

**Comment by gbrueckl** [comment]
even after this change I still could not execute the init-scripts on Azure Databricks cluster 5.3

**Comment by rapoth** [comment]
CC: @suhsteve 

@gbrueckl : Working on a testing this. Sorry for the inconvenience!

**Comment by rapoth** [comment]
@gbrueckl : @suhsteve fixed these issues in https://github.com/dotnet/spark/pull/89 and merged it. Could you please try again per your convenience?

**Comment by gbrueckl** [comment]
@rapoth yes looks fine to me in #89

**Comment by rapoth** [comment]
@gbrueckl : Great, thanks! Are you ok closing this PR?

PS: I've approved your https://github.com/dotnet/spark/pull/96 PR. Please feel free to merge that.

**Comment by gbrueckl** [comment]
closed

**Pull request closed without merging**
