### PR TITLE
Clean up vector UDF examples.

### PR DESCRIPTION
**Pull request by eerhardt**
Clean the Vector Udf examples so they are more "apples to apples" comparison.

/cc @bamurtaugh

### CODE REVIEW

**Comment by imback82** [comment]
Btw, when is 0.3 coming out?

**Comment by pgovind** [comment]
> Btw, when is 0.3 coming out?

Today :). I'm bumping up the version now and making a Spark PR locally

**Comment by eerhardt** [comment]
>> Btw, when is 0.3 coming out?
> Today :). I'm bumping up the version now and making a Spark PR locally

We will ensure 0.3 doesn't break Spark before we officially ship 0.3. Because if we need to make a change, we would have to bump the version number.

**Comment by imback82** [comment]
Cool thanks!

**Pull request merged**
