### PR TITLE
Fixes #1078: update: newtonsoft.json package reference version

### LINKED ISSUE #1078: [BUG]: Newtonsoft.Json update for CWE-755 vulnerability
https://github.com/advisories/GHSA-5crp-9r3c-p9vr

**Describe the bug**
Snyk/lgtm et al. are reporting end users' projects vulnerable as a result of a transitive dependency on Newtonsoft.Json 11 in `Microsoft.Spark`.

**To Reproduce**

1. Include `Microsoft.Spark` in a project/solution.
2. Scan with snyk.io, etc.

### PR DESCRIPTION
**Pull request by cutecycle**
We are excited to review your PR.

So we can do the best job, please check:

- [x] There's a descriptive title that will make sense to other developers some time from now. 
- [x] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [x] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [x] You have included any necessary tests in the same PR.

# Changes
Fixes #1078 

 * Update `csproj` to the latest `Newtonsoft.Json`.

### CODE REVIEW

**Comment by cutecycle** [comment]
I'm not sure how to request review from a PR that started as a draft... @Niharikadutta ?

**Review by Niharikadutta — APPROVED** [review]
LGTM, thanks @cutecycle !

**Comment by Niharikadutta** [comment]
@suhsteve can you also review please?

**Comment by cutecycle** [comment]
linking description since I don't have issue link permission: https://github.com/dotnet/spark/issues/1078

**Comment by AFFogarty** [comment]
LGTM, thanks @cutecycle !

**Review by AFFogarty — APPROVED** [review]

**Pull request merged**
