### PR TITLE
Update Apache.Arrow reference to v0.14.

### PR DESCRIPTION
**Pull request by eerhardt**
Updating to the latest Arrow version which allows us to simplify some code, and brings in the latest perf fixes.

### CODE REVIEW

**Comment by imback82** [comment]
Looks like TPCH build is failing.

**Comment by eerhardt** [comment]
I'll fix it tomorrow.

**Comment by eerhardt** [comment]
Should be fixed now.

**Comment by imback82** [comment]
Looks like E2E is failing now. Does it repro locally?

**Comment by eerhardt** [comment]
> Looks like E2E is failing now. 

The root cause for the failure is https://issues.apache.org/jira/browse/ARROW-5908. I'm working on getting a PR up for that fix. If I can get it into the next service release of Arrow, I will update dotnet/spark with it.

If not, there is a simple workaround I can do in the tests until we get the fix.

**Comment by eerhardt** [comment]
Apache Arrow is planning a `0.14.1` release soon. The two fixes in the C# library will be in it. I will wait for that version to ship, and then update this PR.

The fixes in the patched version are:

https://github.com/apache/arrow/pull/4836
https://github.com/apache/arrow/pull/4851

**Comment by eerhardt** [comment]
@imback82 @suhsteve - Apache.Arrow 0.14.1 was released yesterday. I've updated to that version which should unblock this PR. Please take a look.

**Pull request merged**
