### PR TITLE
Update MDA to 0.18.0

### PR DESCRIPTION
**Pull request by pgovind**
Fixes https://github.com/dotnet/spark/issues/948

Just updating the version of the MDA dependency. In theory, CI should be fine. Let's find out

cc @imback82 @rapoth @eerhardt @suhsteve

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]

**Comment by imback82** [comment]
@pgovind are there any breaking changes in public APIs (which may not be covered by the CI)?

**Comment by pgovind** [comment]
> are there any breaking changes in public APIs 

Just did a quick check of the 0.18.0 release. No breaking changes

**Comment by imback82** [comment]
> 
> Just did a quick check of the 0.18.0 release. No breaking changes

From 0.4.0 to 0.18.0, right?

**Comment by eerhardt** [comment]
> From 0.4.0 to 0.18.0, right?

Yes. We moved the DataFrame library to the dotnet/machinelearning repo, and are using the versioning pattern in that repo going forward.

**Review by suhsteve — APPROVED** [review]

**Comment by Niharikadutta** [comment]
@pgovind is this PR ready to merge? Can you update this with the latest `main`?

**Review by imback82 — APPROVED** [review]
LGTM, thanks @pgovind!

**Pull request merged**
