### PR TITLE
Spark 3.1.0 APIs - Catalog

### PR DESCRIPTION
**Pull request by suhsteve**
PR adds support for the following APIs added in Spark 3.1.0 and adds missing `createTable` APIs:

**Catalog**
Introduced in Spark 3.1.0
```scala
def createTable(tableName: String, source: String, description: String, options: Map[String, String]): DataFrame
def createTable(tableName: String, source: String, schema: StructType, description: String, options: Map[String, String]): DataFrame
```

Missing createTable APIs
```scala
def createTable(tableName: String, source: String, options: Map[String, String]): DataFrame
def createTable(tableName: String, source: String, schema: StructType, options: Map[String, String]): DataFrame
```

### CODE REVIEW

**Review by imback82 — APPROVED** [review]
LGTM, thanks @suhsteve!

**Comment by imback82** [comment]
Is the following a random failure we need to revisit?
```
 Failed Microsoft.Spark.E2ETest.IpcTests.StreamingQueryManagerTests.TestSignaturesV2_3_X [470 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 2
Actual:   3
  Stack Trace:
     at Microsoft.Spark.E2ETest.IpcTests.StreamingQueryManagerTests.TestSignaturesV2_3_X() in D:\a\1\s\dotnet-spark\src\csharp\Microsoft.Spark.E2ETest\IpcTests\Sql\Streaming\StreamingQueryManagerTests.cs:line 46

```

**Comment by suhsteve** [comment]
> Is the following a random failure we need to revisit?
> 
> ```
>  Failed Microsoft.Spark.E2ETest.IpcTests.StreamingQueryManagerTests.TestSignaturesV2_3_X [470 ms]
>   Error Message:
>    Assert.Equal() Failure
> Expected: 2
> Actual:   3
>   Stack Trace:
>      at Microsoft.Spark.E2ETest.IpcTests.StreamingQueryManagerTests.TestSignaturesV2_3_X() in D:\a\1\s\dotnet-spark\src\csharp\Microsoft.Spark.E2ETest\IpcTests\Sql\Streaming\StreamingQueryManagerTests.cs:line 46
> ```

May be something to look into.  Could be from other streaming queries from other tests that haven't been stopped.

**Comment by suhsteve** [comment]
> > Is the following a random failure we need to revisit?
> > ```
> >  Failed Microsoft.Spark.E2ETest.IpcTests.StreamingQueryManagerTests.TestSignaturesV2_3_X [470 ms]
> >   Error Message:
> >    Assert.Equal() Failure
> > Expected: 2
> > Actual:   3
> >   Stack Trace:
> >      at Microsoft.Spark.E2ETest.IpcTests.StreamingQueryManagerTests.TestSignaturesV2_3_X() in D:\a\1\s\dotnet-spark\src\csharp\Microsoft.Spark.E2ETest\IpcTests\Sql\Streaming\StreamingQueryManagerTests.cs:line 46
> > ```
> 
> May be something to look into. Could be from other streaming queries from other tests that haven't been stopped.

I think we can just modify it and not validate the length since we are only interested in checking that JVM calls are successful.

**Comment by imback82** [comment]
> I think we can just modify it and not validate the length since we are only interested in checking that JVM calls are successful.

We should first investigate the root cause. I will create an issue to follow up.

**Pull request merged**
